"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronDown, CirclePlay, Clock3, Download, Film, Globe2, Laugh, LoaderCircle, Menu, Mic2, Newspaper, RefreshCw, Search, Send, ShieldCheck, Sparkles, WandSparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";

const Youtube = Send;

const fallbackStories=[
 {id:1,place:"TOKYO",topic:"TECH",time:"12 MIN AGO",title:"Tokyo tests AI traffic lights that predict the next traffic jam",dek:"The system changes signal timing before congestion builds.",sources:4,score:94,tone:"The traffic light finally got promoted from one-button management.",accent:"lime",mark:"AI"},
 {id:2,place:"LONDON",topic:"CULTURE",time:"34 MIN AGO",title:"Museum asks the public to rename its most mysterious objects",dek:"Thousands of gloriously unscientific suggestions arrived overnight.",sources:3,score:89,tone:"Historians call it crowdsourcing. The internet calls it Tuesday.",accent:"orange",mark:"?!"},
 {id:3,place:"BOSTON",topic:"SCIENCE",time:"1 HR AGO",title:"Researchers teach a robot to tidy rooms without a map",dek:"It identifies clutter, plans a route and puts objects back by itself.",sources:5,score:96,tone:"Your laundry chair has officially been put on notice.",accent:"blue",mark:"R"}
];
const styles=[
 {id:"animated",name:"Animated explainer",desc:"Bold motion graphics",icon:"✦"},
 {id:"faceless",name:"Faceless news",desc:"B-roll + captions",icon:"▶"},
 {id:"presenter",name:"AI presenter",desc:"Host-led delivery",icon:"◉"},
 {id:"meme",name:"Meme cut",desc:"Fast, punchy edits",icon:"⚡"}
];
const beats=[["00–03","HOOK","A robot learned to clean a room. Humanity immediately asked if it also does taxes."],["04–16","THE FACT","Researchers built a system that spots clutter and plans its own cleanup route—without a map."],["17–34","THE TURN","It learned in days. Your laundry chair has been holding the same meeting since 2019."],["35–45","CLOSE","Useful helper, or the beginning of a very judgmental roommate?"]];
type Stage="setup"|"script"|"video"|"published";
type Story=(typeof fallbackStories)[number]&{url?:string;domain?:string;verified?:boolean};
type AiPackage={humorAngle:string;youtubeTitle:string;youtubeDescription:string;beats:Array<{time:string;label:string;narration:string;visual:string}>;safetyNotes:string[]};

const palettes={lime:{accent:"#d9ff57",glow:"#789f12"},orange:{accent:"#ff8a5b",glow:"#ca4f21"},blue:{accent:"#70d7ff",glow:"#178aae"}} as const;
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function lines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/);const result:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){result.push(line);line=word}else line=test}if(line)result.push(line);return result}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,55)||"worldwise-video"}

export default function Home(){
 const [stories,setStories]=useState<Story[]>(fallbackStories); const [selected,setSelected]=useState(3); const [stage,setStage]=useState<Stage>("setup"); const [videoStyle,setVideoStyle]=useState("animated"); const [voice]=useState("Warm storyteller"); const [category,setCategory]=useState("top"); const [loading,setLoading]=useState(true); const [feed,setFeed]=useState("Connecting…"); const [aiPackage,setAiPackage]=useState<AiPackage|null>(null); const [generating,setGenerating]=useState(false); const [aiError,setAiError]=useState(""); const [rendering,setRendering]=useState(false); const [renderProgress,setRenderProgress]=useState(0); const [renderError,setRenderError]=useState(""); const [videoUrl,setVideoUrl]=useState(""); const videoRef=useRef<HTMLVideoElement>(null);
 const story=useMemo(()=>stories.find(s=>s.id===selected)||stories[0]||fallbackStories[0],[stories,selected]);
 const refresh=async(next=category)=>{setLoading(true);setFeed("Refreshing…");try{const response=await fetch(`/api/news?category=${next}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {stories:Story[];provider:string};if(!data.stories?.length)throw new Error();setStories(data.stories);setSelected(data.stories[0].id);setStage("setup");setFeed(`Live · ${data.provider}`)}catch{setStories(fallbackStories);setSelected(fallbackStories[0].id);setFeed("Fallback feed")}finally{setLoading(false)}};
 useEffect(()=>{void refresh("top")},[]);
 useEffect(()=>()=>{if(videoUrl)URL.revokeObjectURL(videoUrl)},[videoUrl]);
 const choose=(id:number)=>{setSelected(id);setStage("setup");setAiPackage(null);setAiError("");setRenderError("");setVideoUrl("")};
 const generateScript=async()=>{setGenerating(true);setAiError("");try{const response=await fetch("/api/generate-script",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:story.title,summary:story.dek,sourceUrl:story.url,style:videoStyle,voice,sources:story.sources,verified:story.verified})});const data=await response.json() as {package?:AiPackage;error?:string};if(!response.ok||!data.package)throw new Error(data.error||"FAILED");setAiPackage(data.package);setStage("script")}catch(error){setAiError(error instanceof Error&&error.message==="AI_SETUP_REQUIRED"?"Add your Google AI Studio API key in Site settings to activate Gemini generation.":"AI generation failed. Please try again.")}finally{setGenerating(false)}};
 const updateBeat=(index:number,narration:string)=>setAiPackage(current=>current?{...current,beats:current.beats.map((beat,i)=>i===index?{...beat,narration}:beat)}:current);
 const renderVideo=async()=>{
  if(!aiPackage||rendering)return;setRendering(true);setRenderProgress(3);setRenderError("");setVideoUrl("");
  let audioContext:AudioContext|null=null;
  try{
   const narration=aiPackage.beats.map(beat=>beat.narration.trim()).filter(Boolean).join(" ");
   const response=await fetch("/api/generate-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({narration,voice:"Kore"})});
   if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string;reason?:string;providerStatus?:number};throw new Error(data.reason||data.error||`VOICE_HTTP_${response.status}`)}
   setRenderProgress(15);const audioBytes=await response.arrayBuffer();audioContext=new AudioContext();await audioContext.resume();const audioBuffer=await audioContext.decodeAudioData(audioBytes.slice(0));
   const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("CANVAS_FAILED");
   const canvasStream=canvas.captureStream(30);const destination=audioContext.createMediaStreamDestination();const source=audioContext.createBufferSource();source.buffer=audioBuffer;source.connect(destination);
   const stream=new MediaStream([...canvasStream.getVideoTracks(),...destination.stream.getAudioTracks()]);
   const types=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"];const mimeType=types.find(type=>MediaRecorder.isTypeSupported(type))||"";const recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:6_000_000}:undefined);const chunks:BlobPart[]=[];recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};
   const finished=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error("RECORDING_FAILED"));recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||"video/webm"}))});
   const palette=palettes[(story.accent as keyof typeof palettes)]||palettes.lime;const duration=audioBuffer.duration;const startAt=audioContext.currentTime+.2;
   const draw=(elapsed:number)=>{const progress=Math.min(1,elapsed/duration);const beatIndex=Math.min(aiPackage.beats.length-1,Math.floor(progress*aiPackage.beats.length));const beat=aiPackage.beats[beatIndex];const local=(progress*aiPackage.beats.length)%1;
    const gradient=ctx.createLinearGradient(0,0,1080,1920);gradient.addColorStop(0,"#11130f");gradient.addColorStop(.62,"#20251c");gradient.addColorStop(1,"#0b0c0a");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1920);
    ctx.globalAlpha=.18;ctx.fillStyle=palette.accent;ctx.beginPath();ctx.arc(850+Math.sin(elapsed)*45,330,370,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
    ctx.fillStyle="#f6f5ed";ctx.font="800 32px Arial";ctx.fillText("WORLDWISE COMEDY",70,90);ctx.textAlign="right";ctx.fillStyle=palette.accent;ctx.fillText("45-SECOND NEWS",1010,90);ctx.textAlign="left";
    ctx.fillStyle="#363a32";rounded(ctx,70,130,940,12,6);ctx.fillStyle=palette.accent;rounded(ctx,70,130,940*progress,12,6);
    ctx.fillStyle=palette.accent;rounded(ctx,70,225,270,62,31);ctx.fillStyle="#11130f";ctx.font="900 28px Arial";ctx.textAlign="center";ctx.fillText(beat.label,205,266);ctx.textAlign="left";
    ctx.fillStyle="#aeb4a6";ctx.font="700 27px Arial";ctx.fillText(`${story.place}  ·  ${story.topic}`,70,360);
    ctx.save();ctx.translate(70,520+Math.sin(local*Math.PI)*-10);ctx.globalAlpha=Math.min(1,local*5);ctx.fillStyle="#ffffff";ctx.font="900 70px Arial";const wrapped=lines(ctx,beat.narration.toUpperCase(),920);wrapped.slice(0,8).forEach((line,i)=>ctx.fillText(line,0,i*86));ctx.restore();
    ctx.fillStyle="#aeb4a6";ctx.font="500 28px Arial";const visualLines=lines(ctx,beat.visual,860);visualLines.slice(0,2).forEach((line,i)=>ctx.fillText(line,70,1420+i*40));
    for(let i=0;i<22;i++){const height=30+Math.abs(Math.sin(elapsed*4+i*.55))*110;ctx.fillStyle=i%3===0?palette.accent:"#596052";rounded(ctx,70+i*43,1660-height/2,18,height,9)}
    ctx.fillStyle="#747b6e";ctx.font="600 24px Arial";ctx.fillText(story.domain?`SOURCE: ${story.domain.toUpperCase()}`:"SOURCE LINK INCLUDED",70,1810);ctx.textAlign="right";ctx.fillStyle="#f6f5ed";ctx.fillText(`${Math.ceil(Math.max(0,duration-elapsed))} SEC`,1010,1810);ctx.textAlign="left";
   };
   draw(0);recorder.start(250);source.start(startAt);const tick=()=>{const elapsed=Math.max(0,audioContext!.currentTime-startAt);draw(elapsed);setRenderProgress(15+Math.round(Math.min(1,elapsed/duration)*82));if(elapsed<duration)requestAnimationFrame(tick)};requestAnimationFrame(tick);
   await new Promise<void>(resolve=>{source.onended=()=>resolve()});await new Promise(resolve=>setTimeout(resolve,180));recorder.stop();const blob=await finished;stream.getTracks().forEach(track=>track.stop());const url=URL.createObjectURL(blob);setVideoUrl(url);setRenderProgress(100);setStage("video");
  }catch(error){const code=error instanceof Error?error.message:"UNKNOWN";const message=code==="AI_SETUP_REQUIRED"?"Gemini API key is missing in Cloudflare.":code.includes("PERMISSION_DENIED")||code.includes("HTTP_403")?"Gemini TTS is not enabled for this API key/project.":code.includes("RESOURCE_EXHAUSTED")||code.includes("HTTP_429")?"Gemini TTS free quota is exhausted. Wait and try again.":code.includes("UNAUTHENTICATED")||code.includes("HTTP_401")?"Gemini rejected the API key.":code.includes("NotSupported")||code.includes("MediaRecorder")?"This browser cannot record WebM. Use current Chrome or Edge.":`Render stopped at: ${code}. Try once more; if it repeats, this code identifies the cause.`;setRenderError(message)}finally{if(audioContext)void audioContext.close();setRendering(false)}
 };
 return <main className="app-shell">
  <header className="masthead"><div className="logo"><span><Laugh size={22}/></span>WorldWise<em>STUDIO</em></div><div className="steps"><span className={stage!=="setup"?"done":"active"}><b>1</b> Script</span><i/><span className={stage==="video"||stage==="published"?"done":stage==="script"?"active":""}><b>2</b> Render</span><i/><span className={stage==="published"?"done":stage==="video"?"active":""}><b>3</b> Approve</span><i/><span className={stage==="published"?"active":""}><b>4</b> Publish</span></div><div className="head-actions"><button className="icon-button"><Search size={19}/></button><Button className="new-video"><Sparkles size={16}/> New video</Button><button className="menu"><Menu/></button></div></header>
  <div className="studio">
   <aside className="story-browser"><div className="browser-head"><div><span className="overline">LIVE NEWS FEED</span><h1>Choose a story</h1></div><button className="dots" onClick={()=>void refresh()} aria-label="Refresh news">{loading?<LoaderCircle className="spin"/>:<RefreshCw/>}</button></div><div className="source-status"><span className="pulse"/><b>{loading?"Scanning global coverage":`${stories.length} stories loaded`}</b><span>{feed}</span></div><div className="topic-tabs">{[["top","Top stories"],["world","World"],["science","Science"]].map(([id,label])=><button key={id} className={category===id?"selected":""} onClick={()=>{setCategory(id);void refresh(id)}}>{label}</button>)}</div>
    <div className="story-list">{stories.map(item=><button key={item.id} onClick={()=>choose(item.id)} className={`story ${selected===item.id?"selected":""}`}><span className={`story-mark ${item.accent}`}>{item.mark}</span><span className="story-copy"><span className="story-meta">{item.place} · {item.time}</span><strong>{item.title}</strong><span className="story-proof"><ShieldCheck size={14}/>{item.sources} coverage source{item.sources===1?"":"s"} <i>{item.verified?"Multi-source":"Needs verification"}</i></span></span></button>)}</div><button className="all-stories" onClick={()=>void refresh()}><Newspaper size={17}/> Refresh global news <ArrowRight size={16}/></button>
   </aside>
   <section className="canvas">
    <div className="canvas-top"><div><span className="overline">SELECTED STORY</span><div className="tags"><span>{story.topic}</span><span>{story.place}</span><span><Clock3/> {story.time}</span></div></div><button className="close"><X/></button></div>
    <div className="story-title"><h2>{story.title}</h2><p>{story.dek}</p>{story.url&&<a className="source-link" href={story.url} target="_blank" rel="noreferrer">Open original source · {story.domain}<ArrowRight/></a>}</div>
    {stage==="setup"&&<><div className="workflow-note"><span>1</span><div><b>First create the script and visual plan</b><p>No video credits are used until you approve the plan.</p></div></div><div className="creation-layout"><div className="style-section"><span className="overline">VIDEO STYLE</span><h3>How should this story feel?</h3><div className="style-grid">{styles.map(s=><button key={s.id} onClick={()=>setVideoStyle(s.id)} className={videoStyle===s.id?"selected":""}><span>{s.icon}</span><b>{s.name}</b><small>{s.desc}</small>{videoStyle===s.id&&<i><Check/></i>}</button>)}</div><label>Voice</label><button className="select-control"><span><b>{voice}</b><small>English (US) · Conversational</small></span><ChevronDown/></button></div><div className={`poster ${story.accent}`}><div className="poster-top"><span>STYLE PREVIEW</span><span>9:16</span></div><div className="poster-orbit"><span className="orb one"/><span className="orb two"/><span className="face"><b>{story.mark}</b></span></div><div className="poster-copy"><span>{styles.find(s=>s.id===videoStyle)?.name.toUpperCase()}</span><strong><>TODAY'S STORY<br/><u>IN 45</u> SECONDS.</></strong></div></div></div><div className="approval-bar"><div><ShieldCheck/><span><b>{story.verified?"Multi-source coverage detected":"Verification still required"}</b><small>Open the original source before approving factual claims.</small></span></div><div className="generate-wrap"><Button onClick={()=>void generateScript()} disabled={generating} className="create-button">{generating?<LoaderCircle className="spin"/>:<WandSparkles/>}{generating?"Writing script…":"Generate AI script & plan"}{!generating&&<ArrowRight/>}</Button>{aiError&&<p className="ai-error">{aiError}</p>}</div></div></>}

    {stage==="script"&&<section className="draft full"><div className="stage-banner"><span>1</span><div><b>Review the script</b><p>Edit the words, then create the narration and real video.</p></div><em>AWAITING APPROVAL</em></div><div className="draft-head"><div><span className="overline">SCRIPT & SHOT PLAN</span><h3>{styles.find(s=>s.id===videoStyle)?.name} · about 45 seconds</h3></div><span className="draft-ready"><Check/> AI draft ready</span></div><div className="beats">{(aiPackage?.beats||beats.map(([time,label,narration])=>({time,label,narration,visual:"Visual direction pending"}))).map((beat,index)=><div className="beat" key={beat.label}><time>{beat.time}</time><b>{beat.label}</b><div><p contentEditable suppressContentEditableWarning onBlur={event=>updateBeat(index,event.currentTarget.textContent||"")}>{beat.narration}</p><small>{beat.visual}</small></div><button aria-label={`Preview ${beat.label}`}><CirclePlay/></button></div>)}</div>{aiPackage&&<div className="ai-notes"><b>Comedy angle</b><p>{aiPackage.humorAngle}</p>{aiPackage.safetyNotes.length>0&&<small>Review: {aiPackage.safetyNotes.join(" · ")}</small>}</div>}<div className="draft-footer"><button className="secondary" onClick={()=>setStage("setup")} disabled={rendering}>Change style</button><div className="assets"><span><Mic2/> Gemini narration</span><span><Globe2/> Sources linked</span></div><div className="render-action"><Button onClick={()=>void renderVideo()} disabled={rendering||!aiPackage} className="publish-button">{rendering?<LoaderCircle className="spin"/>:<Film/>}{rendering?`Rendering ${renderProgress}%`:"Approve & render video"}</Button>{rendering&&<div className="render-meter"><i style={{width:`${renderProgress}%`}}/></div>}{renderError&&<p className="render-error">{renderError}</p>}</div></div></section>}

    {stage==="video"&&<section className="video-review"><div className="stage-banner"><span>2</span><div><b>Your real video is ready</b><p>Watch it, download the WebM file, and approve the result before publishing.</p></div><em>FINAL REVIEW</em></div><div className="review-grid"><div className="video-player">{videoUrl?<video ref={videoRef} src={videoUrl} controls playsInline preload="metadata"/>:<div className={`rendered-video ${story.accent}`}><LoaderCircle className="spin"/></div>}<a className="download-video" href={videoUrl} download={`${slug(aiPackage?.youtubeTitle||story.title)}.webm`}><Download/> Download video</a></div><div className="publish-card"><span className="overline">YOUTUBE DETAILS</span><h3>{story.title}</h3><label>Title</label><input defaultValue={aiPackage?.youtubeTitle||story.title}/><label>Description</label><textarea defaultValue={aiPackage?.youtubeDescription||story.dek}/><div className="check-row"><Check/> Narration, animated captions and source label included</div><Button disabled className="youtube-button"><Youtube/> YouTube connection comes next</Button><p className="publish-note">Download works now. Direct channel publishing will be enabled after YouTube OAuth is connected.</p><button className="secondary wide" onClick={()=>setStage("script")}>Back to script</button></div></div></section>}
   </section>
  </div>
 </main>
}
