"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, ChevronDown, CirclePlay, Clock3, Film, Globe2, Laugh, LoaderCircle, Menu, Mic2, MoreHorizontal, Newspaper, Play, RefreshCw, Search, Send, ShieldCheck, Sparkles, WandSparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";

const Youtube = Send;

const fallbackStories=[
 {id:1,place:"TOKYO",topic:"TECH",time:"12 MIN AGO",title:"Tokyo tests AI traffic lights that predict the next traffic jam",dek:"The system changes signal timing before congestion builds.",sources:4,score:94,tone:"The traffic light finally got promoted from one-button management.",accent:"lime",mark:"AI"},
 {id:2,place:"LONDON",topic:"CULTURE",time:"34 MIN AGO",title:"Museum asks the public to rename its most mysterious objects",dek:"Thousands of gloriously unscientific suggestions arrived overnight.",sources:3,score:89,tone:"Historians call it crowdsourcing. The internet calls it Tuesday.",accent:"orange",mark:"?!"},
 {id:3,place:"BOSTON",topic:"SCIENCE",time:"1 HR AGO",title:"Researchers teach a robot to tidy rooms without a map",dek:"It identifies clutter, plans a route and puts objects back by itself.",sources:5,score:96,tone:"Your laundry chair has officially been put on notice.",accent:"blue",mark:"R"}
];
const styles=[
 {id:"animated",name:"Animated explainer",desc:"Bold motion graphics",icon:"✦"},
 {id:"faceless",name:"Faceless news",desc:"B-roll + captions",icon:"▶"},
 {id:"presenter",name:"AI presenter",desc:"Host-led delivery",icon:"◉"},
 {id:"meme",name:"Meme cut",desc:"Fast, punchy edits",icon:"⚡"}
];
const beats=[["00–03","HOOK","A robot learned to clean a room. Humanity immediately asked if it also does taxes."],["04–16","THE FACT","Researchers built a system that spots clutter and plans its own cleanup route—without a map."],["17–34","THE TURN","It learned in days. Your laundry chair has been holding the same meeting since 2019."],["35–45","CLOSE","Useful helper, or the beginning of a very judgmental roommate?"]];
type Stage="setup"|"script"|"video"|"published";
type Story=(typeof fallbackStories)[number]&{url?:string;domain?:string;verified?:boolean};
type AiPackage={humorAngle:string;youtubeTitle:string;youtubeDescription:string;beats:Array<{time:string;label:string;narration:string;visual:string}>;safetyNotes:string[]};

export default function Home(){
 const [stories,setStories]=useState<Story[]>(fallbackStories); const [selected,setSelected]=useState(3); const [stage,setStage]=useState<Stage>("setup"); const [videoStyle,setVideoStyle]=useState("animated"); const [voice]=useState("Warm storyteller"); const [category,setCategory]=useState("top"); const [loading,setLoading]=useState(true); const [feed,setFeed]=useState("Connecting…"); const [aiPackage,setAiPackage]=useState<AiPackage|null>(null); const [generating,setGenerating]=useState(false); const [aiError,setAiError]=useState("");
 const story=useMemo(()=>stories.find(s=>s.id===selected)||stories[0]||fallbackStories[0],[stories,selected]);
 const refresh=async(next=category)=>{setLoading(true);setFeed("Refreshing…");try{const response=await fetch(`/api/news?category=${next}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {stories:Story[];provider:string};if(!data.stories?.length)throw new Error();setStories(data.stories);setSelected(data.stories[0].id);setStage("setup");setFeed(`Live · ${data.provider}`)}catch{setStories(fallbackStories);setSelected(fallbackStories[0].id);setFeed("Fallback feed")}finally{setLoading(false)}};
 useEffect(()=>{void refresh("top")},[]);
 const choose=(id:number)=>{setSelected(id);setStage("setup");setAiPackage(null);setAiError("")};
 const generateScript=async()=>{setGenerating(true);setAiError("");try{const response=await fetch("/api/generate-script",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:story.title,summary:story.dek,sourceUrl:story.url,style:videoStyle,voice,sources:story.sources,verified:story.verified})});const data=await response.json() as {package?:AiPackage;error?:string};if(!response.ok||!data.package)throw new Error(data.error||"FAILED");setAiPackage(data.package);setStage("script")}catch(error){setAiError(error instanceof Error&&error.message==="AI_SETUP_REQUIRED"?"Add your Google AI Studio API key in Site settings to activate Gemini generation.":"AI generation failed. Please try again.")}finally{setGenerating(false)}};
 return <main className="app-shell">
  <header className="masthead"><div className="logo"><span><Laugh size={22}/></span>WorldWise<em>STUDIO</em></div><div className="steps"><span className={stage!=="setup"?"done":"active"}><b>1</b> Script</span><i/><span className={stage==="video"||stage==="published"?"done":stage==="script"?"active":""}><b>2</b> Render</span><i/><span className={stage==="published"?"done":stage==="video"?"active":""}><b>3</b> Approve</span><i/><span className={stage==="published"?"active":""}><b>4</b> Publish</span></div><div className="head-actions"><button className="icon-button"><Search size={19}/></button><Button className="new-video"><Sparkles size={16}/> New video</Button><button className="menu"><Menu/></button></div></header>
  <div className="studio">
   <aside className="story-browser"><div className="browser-head"><div><span className="overline">LIVE NEWS FEED</span><h1>Choose a story</h1></div><button className="dots" onClick={()=>void refresh()} aria-label="Refresh news">{loading?<LoaderCircle className="spin"/>:<RefreshCw/>}</button></div><div className="source-status"><span className="pulse"/><b>{loading?"Scanning global coverage":`${stories.length} stories loaded`}</b><span>{feed}</span></div><div className="topic-tabs">{[["top","Top stories"],["world","World"],["science","Science"]].map(([id,label])=><button key={id} className={category===id?"selected":""} onClick={()=>{setCategory(id);void refresh(id)}}>{label}</button>)}</div>
    <div className="story-list">{stories.map(item=><button key={item.id} onClick={()=>choose(item.id)} className={`story ${selected===item.id?"selected":""}`}><span className={`story-mark ${item.accent}`}>{item.mark}</span><span className="story-copy"><span className="story-meta">{item.place} · {item.time}</span><strong>{item.title}</strong><span className="story-proof"><ShieldCheck size={14}/>{item.sources} coverage source{item.sources===1?"":"s"} <i>{item.verified?"Multi-source":"Needs verification"}</i></span></span></button>)}</div><button className="all-stories" onClick={()=>void refresh()}><Newspaper size={17}/> Refresh global news <ArrowRight size={16}/></button>
   </aside>
   <section className="canvas">
    <div className="canvas-top"><div><span className="overline">SELECTED STORY</span><div className="tags"><span>{story.topic}</span><span>{story.place}</span><span><Clock3/> {story.time}</span></div></div><button className="close"><X/></button></div>
    <div className="story-title"><h2>{story.title}</h2><p>{story.dek}</p>{story.url&&<a className="source-link" href={story.url} target="_blank" rel="noreferrer">Open original source · {story.domain}<ArrowRight/></a>}</div>
    {stage==="setup"&&<><div className="workflow-note"><span>1</span><div><b>First create the script and visual plan</b><p>No video credits are used until you approve the plan.</p></div></div><div className="creation-layout"><div className="style-section"><span className="overline">VIDEO STYLE</span><h3>How should this story feel?</h3><div className="style-grid">{styles.map(s=><button key={s.id} onClick={()=>setVideoStyle(s.id)} className={videoStyle===s.id?"selected":""}><span>{s.icon}</span><b>{s.name}</b><small>{s.desc}</small>{videoStyle===s.id&&<i><Check/></i>}</button>)}</div><label>Voice</label><button className="select-control"><span><b>{voice}</b><small>English (US) · Conversational</small></span><ChevronDown/></button></div><div className={`poster ${story.accent}`}><div className="poster-top"><span>STYLE PREVIEW</span><span>9:16</span></div><div className="poster-orbit"><span className="orb one"/><span className="orb two"/><span className="face"><b>{story.mark}</b></span></div><div className="poster-copy"><span>{styles.find(s=>s.id===videoStyle)?.name.toUpperCase()}</span><strong><>TODAY'S STORY<br/><u>IN 45</u> SECONDS.</></strong></div></div></div><div className="approval-bar"><div><ShieldCheck/><span><b>{story.verified?"Multi-source coverage detected":"Verification still required"}</b><small>Open the original source before approving factual claims.</small></span></div><div className="generate-wrap"><Button onClick={()=>void generateScript()} disabled={generating} className="create-button">{generating?<LoaderCircle className="spin"/>:<WandSparkles/>}{generating?"Writing script…":"Generate AI script & plan"}{!generating&&<ArrowRight/>}</Button>{aiError&&<p className="ai-error">{aiError}</p>}</div></div></>}

    {stage==="script"&&<section className="draft full"><div className="stage-banner"><span>1</span><div><b>Review the script</b><p>Edit the words before spending credits on rendering.</p></div><em>AWAITING APPROVAL</em></div><div className="draft-head"><div><span className="overline">SCRIPT & SHOT PLAN</span><h3>{styles.find(s=>s.id===videoStyle)?.name} · 45 seconds</h3></div><span className="draft-ready"><Check/> AI draft ready</span></div><div className="beats">{(aiPackage?.beats||beats.map(([time,label,narration])=>({time,label,narration,visual:"Visual direction pending"}))).map(beat=><div className="beat" key={beat.label}><time>{beat.time}</time><b>{beat.label}</b><div><p contentEditable suppressContentEditableWarning>{beat.narration}</p><small>{beat.visual}</small></div><button><CirclePlay/></button></div>)}</div>{aiPackage&&<div className="ai-notes"><b>Comedy angle</b><p>{aiPackage.humorAngle}</p>{aiPackage.safetyNotes.length>0&&<small>Review: {aiPackage.safetyNotes.join(" · ")}</small>}</div>}<div className="draft-footer"><button className="secondary" onClick={()=>setStage("setup")}>Change style</button><div className="assets"><span><Mic2/> Voice plan ready</span><span><Globe2/> Sources linked</span></div><Button onClick={()=>setStage("video")} className="publish-button"><Film/> Approve & render video</Button></div></section>}

    {(stage==="video"||stage==="published")&&<section className="video-review"><div className="stage-banner"><span>{stage==="published"?"✓":"2"}</span><div><b>{stage==="published"?"Published successfully":"Video ready for final approval"}</b><p>{stage==="published"?"Your channel will report processing and analytics here.":"Watch the complete video before sending it to your channel."}</p></div><em>{stage==="published"?"COMPLETE":"FINAL GATE"}</em></div><div className="review-grid"><div className={`rendered-video ${story.accent}`}><div className="video-chrome"><span>00:00</span><span>00:45</span></div><div className="render-copy"><small>WORLDWISE EXPLAINS</small><strong>YOUR STORY<br/>IS READY<br/>TO WATCH.</strong></div><button><Play fill="currentColor"/></button></div><div className="publish-card"><span className="overline">YOUTUBE DETAILS</span><h3>{story.title}</h3><label>Title</label><input defaultValue={aiPackage?.youtubeTitle||story.title}/><label>Description</label><textarea defaultValue={aiPackage?.youtubeDescription||story.dek}/><div className="check-row"><Check/> Captions and source links included</div>{stage==="published"?<div className="published-box"><Youtube/><span><b>Sent to your channel</b><small>Demo publishing job completed</small></span></div>:<Button onClick={()=>setStage("published")} className="youtube-button"><Youtube/> Approve & publish to YouTube</Button>}<button className="secondary wide" onClick={()=>setStage("script")}>Back to script</button></div></div></section>}
   </section>
  </div>
 </main>
}
