"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronDown, CirclePlay, Clock3, Download, Film, Globe2, Laugh, LoaderCircle, Menu, Mic2, Newspaper, RefreshCw, Search, Send, ShieldCheck, Sparkles, WandSparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";

const Youtube = Send;

const fallbackStories=[
 {id:1,place:"TOKYO",topic:"TECH",time:"12 MIN AGO",title:"Tokyo tests AI traffic lights that predict the next traffic jam",dek:"The system changes signal timing before congestion builds.",sources:4,score:94,tone:"The traffic light finally got promoted from one-button management.",accent:"lime",mark:"AI"},
 {id:2,place:"LONDON",topic:"CULTURE",time:"34 MIN AGO",title:"Museum asks the public to rename its most mysterious objects",dek:"Thousands of gloriously unscientific suggestions arrived overnight.",sources:3,score:89,tone:"Historians call it crowdsourcing. The internet calls it Tuesday.",accent:"orange",mark:"?!"},
 {id:3,place:"BOSTON",topic:"SCIENCE",time:"1 HR AGO",title:"Researchers teach a robot to tidy rooms without a map",dek:"It identifies clutter, plans a route and puts objects back by itself.",sources:5,score:96,tone:"Your laundry chair has officially been put on notice.",accent:"blue",mark:"R"}
];
const styles=[
 {id:"animated",name:"Animated explainer",desc:"Bold motion graphics",icon:"✦"},
 {id:"faceless",name:"Faceless news",desc:"B-roll + captions",icon:"▶"},
 {id:"presenter",name:"AI presenter",desc:"Host-led delivery",icon:"◉"},
 {id:"meme",name:"Meme cut",desc:"Fast, punchy edits",icon:"⚡"}
];
const beats=[["00–04","HOOK","A robot learned to clean a room. Humanity immediately asked if it also does taxes."],["05–13","THE FACT","It spots clutter and plans its own cleanup route without a map."],["14–23","THE TURN","Your laundry chair has been holding the same meeting since 2019."],["24–30","CLOSE","Useful helper, or a very judgmental roommate?"]];
type Stage="setup"|"script"|"video"|"published";
type Story=(typeof fallbackStories)[number]&{url?:string;domain?:string;verified?:boolean};
type AiPackage={humorAngle:string;youtubeTitle:string;youtubeDescription:string;beats:Array<{time:string;label:string;narration:string;visual:string}>;safetyNotes:string[]};

const palettes={lime:{accent:"#d9ff57",glow:"#789f12"},orange:{accent:"#ff8a5b",glow:"#ca4f21"},blue:{accent:"#70d7ff",glow:"#178aae"}} as const;
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function lines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/);const result:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){result.push(line);line=word}else line=test}if(line)result.push(line);return result}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,55)||"worldwise-video"}
function cartoonPerson(ctx:CanvasRenderingContext2D,x:number,y:number,scale:number,accent:string,reaction="!"){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.lineWidth=14;ctx.lineCap="round";ctx.strokeStyle="#191b17";ctx.fillStyle="#ffd2a6";ctx.beginPath();ctx.arc(0,-110,72,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#191b17";ctx.beginPath();ctx.arc(-24,-120,7,0,Math.PI*2);ctx.arc(24,-120,7,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,-92,25,0,Math.PI);ctx.stroke();ctx.fillStyle=accent;ctx.beginPath();ctx.roundRect(-75,-35,150,190,35);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-55,155);ctx.lineTo(-70,270);ctx.moveTo(55,155);ctx.lineTo(70,270);ctx.moveTo(-70,20);ctx.lineTo(-145,-20);ctx.moveTo(70,20);ctx.lineTo(145,-60);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(125,-175,48,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#191b17";ctx.font="900 42px Arial";ctx.textAlign="center";ctx.fillText(reaction,125,-160);ctx.restore()}
function cartoonScene(ctx:CanvasRenderingContext2D,text:string,accent:string,t:number){const value=text.toLowerCase();const bounce=Math.sin(t*5)*12;ctx.save();ctx.translate(0,bounce);ctx.fillStyle="#f8f5e8";rounded(ctx,70,365,940,670,58);ctx.strokeStyle="#191b17";ctx.lineWidth=12;ctx.strokeRect(82,377,916,646);cartoonPerson(ctx,300,690,1.15,accent,value.includes("?")?"?":"!");ctx.fillStyle="#191b17";ctx.textAlign="center";
 if(/robot|ai|machine|technology/.test(value)){ctx.fillStyle="#c9d8dd";rounded(ctx,610,520,270,300,45);ctx.strokeRect(610,520,270,300);ctx.fillStyle=accent;ctx.beginPath();ctx.arc(680,620,24,0,Math.PI*2);ctx.arc(810,620,24,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#191b17";ctx.beginPath();ctx.moveTo(680,730);ctx.quadraticCurveTo(745,775,810,730);ctx.stroke();ctx.font="900 54px Arial";ctx.fillStyle="#191b17";ctx.fillText("BOT",745,910)}
 else if(/money|tax|bank|price|cost|market|business/.test(value)){ctx.font="900 190px Arial";ctx.fillStyle="#59a96a";ctx.fillText("$",750,760);ctx.font="900 42px Arial";ctx.fillStyle="#191b17";ctx.fillText("CHA-CHING?",750,900)}
 else if(/weather|storm|rain|climate|heat|snow/.test(value)){ctx.fillStyle="#70d7ff";ctx.beginPath();ctx.arc(690,600,90,Math.PI,0);ctx.arc(790,585,115,Math.PI,0);ctx.arc(875,620,75,Math.PI,0);ctx.fill();ctx.font="900 90px Arial";ctx.fillStyle="#27667b";ctx.fillText("☂",780,850)}
 else if(/car|traffic|road|train|plane|travel/.test(value)){ctx.fillStyle=accent;rounded(ctx,590,650,330,150,35);ctx.strokeRect(590,650,330,150);ctx.fillStyle="#191b17";ctx.beginPath();ctx.arc(665,820,45,0,Math.PI*2);ctx.arc(845,820,45,0,Math.PI*2);ctx.fill();ctx.font="900 42px Arial";ctx.fillText("BEEP!",755,570)}
 else if(/phone|internet|social|app|online/.test(value)){ctx.fillStyle="#252923";rounded(ctx,650,490,230,410,38);ctx.fillStyle=accent;rounded(ctx,675,545,180,280,20);ctx.font="900 65px Arial";ctx.fillStyle="#191b17";ctx.fillText("LOL",765,720)}
 else if(/science|research|study|space|moon|planet/.test(value)){ctx.fillStyle="#b58cff";ctx.beginPath();ctx.arc(760,690,145,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=accent;ctx.lineWidth=28;ctx.beginPath();ctx.ellipse(760,690,250,75,-.35,0,Math.PI*2);ctx.stroke();ctx.font="900 43px Arial";ctx.fillStyle="#191b17";ctx.fillText("SCIENCE!",760,920)}
 else if(/government|president|minister|law|election|court/.test(value)){ctx.fillStyle="#fff";rounded(ctx,590,650,350,210,20);ctx.strokeRect(590,650,350,210);ctx.font="900 130px Arial";ctx.fillStyle="#191b17";ctx.fillText("⚖",765,810);ctx.font="900 38px Arial";ctx.fillText("OFFICIAL BUSINESS",765,930)}
 else {ctx.fillStyle="#70d7ff";ctx.beginPath();ctx.arc(760,690,170,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font="900 115px Arial";ctx.fillStyle="#191b17";ctx.fillText("NEWS",760,730);ctx.font="900 42px Arial";ctx.fillText("JUST IN!",760,910)}ctx.restore();ctx.textAlign="left"}

export default function Home(){
 const [stories,setStories]=useState<Story[]>(fallbackStories); const [selected,setSelected]=useState(3); const [stage,setStage]=useState<Stage>("setup"); const [videoStyle,setVideoStyle]=useState("animated"); const [voice]=useState("Warm storyteller"); const [category,setCategory]=useState("top"); const [loading,setLoading]=useState(true); const [feed,setFeed]=useState("Connecting…"); const [aiPackage,setAiPackage]=useState<AiPackage|null>(null); const [generating,setGenerating]=useState(false); const [aiError,setAiError]=useState(""); const [rendering,setRendering]=useState(false); const [renderProgress,setRenderProgress]=useState(0); const [renderError,setRenderError]=useState(""); const [videoUrl,setVideoUrl]=useState(""); const videoRef=useRef<HTMLVideoElement>(null);
 const story=useMemo(()=>stories.find(s=>s.id===selected)||stories[0]||fallbackStories[0],[stories,selected]);
 const refresh=async(next=category)=>{setLoading(true);setFeed("Refreshing…");try{const response=await fetch(`/api/news?category=${next}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {stories:Story[];provider:string};if(!data.stories?.length)throw new Error();setStories(data.stories);setSelected(data.stories[0].id);setStage("setup");setFeed(`Live · ${data.provider}`)}catch{setStories(fallbackStories);setSelected(fallbackStories[0].id);setFeed("Fallback feed")}finally{setLoading(false)}};
 useEffect(()=>{void refresh("top")},[]);
 useEffect(()=>()=>{if(videoUrl)URL.revokeObjectURL(videoUrl)},[videoUrl]);
 const choose=(id:number)=>{setSelected(id);setStage("setup");setAiPackage(null);setAiError("");setRenderError("");setVideoUrl("")};
 const generateScript=async()=>{setGenerating(true);setAiError("");try{const response=await fetch("/api/generate-script",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:story.title,summary:story.dek,sourceUrl:story.url,style:videoStyle,voice,sources:story.sources,verified:story.verified})});const data=await response.json() as {package?:AiPackage;error?:string};if(!response.ok||!data.package)throw new Error(data.error||"FAILED");setAiPackage(data.package);setStage("script")}catch(error){setAiError(error instanceof Error&&error.message==="AI_SETUP_REQUIRED"?"Add your Google AI Studio API key in Site settings to activate Gemini generation.":"AI generation failed. Please try again.")}finally{setGenerating(false)}};
 const updateBeat=(index:number,narration:string)=>setAiPackage(current=>current?{...current,beats:current.beats.map((beat,i)=>i===index?{...beat,narration}:beat)}:current);
 const renderVideo=async()=>{
  if(!aiPackage||rendering)return;setRendering(true);setRenderProgress(3);setRenderError("");setVideoUrl("");
  let audioContext:AudioContext|null=null;
  try{
   const narration=aiPackage.beats.map(beat=>beat.narration.trim()).filter(Boolean).join(" ");
   const response=await fetch("/api/generate-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({narration,voice:"Kore"})});
   if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string;reason?:string;providerStatus?:number};throw new Error(data.reason||data.error||`VOICE_HTTP_${response.status}`)}
   setRenderProgress(15);const audioBytes=await response.arrayBuffer();audioContext=new AudioContext();await audioContext.resume();const audioBuffer=await audioContext.decodeAudioData(audioBytes.slice(0));
   const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("CANVAS_FAILED");
   const canvasStream=canvas.captureStream(30);const destination=audioContext.createMediaStreamDestination();const source=audioContext.createBufferSource();source.buffer=audioBuffer;source.connect(destination);
   const stream=new MediaStream([...canvasStream.getVideoTracks(),...destination.stream.getAudioTracks()]);
   const types=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"];const mimeType=types.find(type=>MediaRecorder.isTypeSupported(type))||"";const recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:6_000_000}:undefined);const chunks:BlobPart[]=[];recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};
   const finished=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error("RECORDING_FAILED"));recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||"video/webm"}))});
   const palette=palettes[(story.accent as keyof typeof palettes)]||palettes.lime;const duration=30;const startAt=audioContext.currentTime+.2;source.playbackRate.value=audioBuffer.duration>29?audioBuffer.duration/29:1;
   const draw=(elapsed:number)=>{const progress=Math.min(1,elapsed/duration);const beatIndex=Math.min(aiPackage.beats.length-1,Math.floor(progress*aiPackage.beats.length));const beat=aiPackage.beats[beatIndex];const local=(progress*aiPackage.beats.length)%1;
    const gradient=ctx.createLinearGradient(0,0,1080,1920);gradient.addColorStop(0,"#11130f");gradient.addColorStop(.62,"#20251c");gradient.addColorStop(1,"#0b0c0a");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1920);
    ctx.globalAlpha=.18;ctx.fillStyle=palette.accent;ctx.beginPath();ctx.arc(850+Math.sin(elapsed)*45,330,370,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
    ctx.fillStyle="#f6f5ed";ctx.font="800 32px Arial";ctx.fillText("WORLDWISE COMEDY",70,90);ctx.textAlign="right";ctx.fillStyle=palette.accent;ctx.fillText("30-SECOND CARTOON",1010,90);ctx.textAlign="left";
    ctx.fillStyle="#363a32";rounded(ctx,70,130,940,12,6);ctx.fillStyle=palette.accent;rounded(ctx,70,130,940*progress,12,6);
    ctx.fillStyle=palette.accent;rounded(ctx,70,225,270,62,31);ctx.fillStyle="#11130f";ctx.font="900 28px Arial";ctx.textAlign="center";ctx.fillText(beat.label,205,266);ctx.textAlign="left";
    ctx.fillStyle="#aeb4a6";ctx.font="700 27px Arial";ctx.fillText(`${story.place}  ·  ${story.topic}`,70,340);cartoonScene(ctx,`${beat.narration} ${beat.visual}`,palette.accent,elapsed);
    ctx.save();ctx.translate(70,1140+Math.sin(local*Math.PI)*-8);ctx.globalAlpha=Math.min(1,local*5);ctx.fillStyle="#ffffff";ctx.font="900 57px Arial";const wrapped=lines(ctx,beat.narration.toUpperCase(),920);wrapped.slice(0,5).forEach((line,i)=>ctx.fillText(line,0,i*68));ctx.restore();
    for(let i=0;i<22;i++){const height=30+Math.abs(Math.sin(elapsed*4+i*.55))*110;ctx.fillStyle=i%3===0?palette.accent:"#596052";rounded(ctx,70+i*43,1660-height/2,18,height,9)}
    ctx.fillStyle="#747b6e";ctx.font="600 24px Arial";ctx.fillText(story.domain?`SOURCE: ${story.domain.toUpperCase()}`:"SOURCE LINK INCLUDED",70,1810);ctx.textAlign="right";ctx.fillStyle="#f6f5ed";ctx.fillText(`${Math.ceil(Math.max(0,duration-elapsed))} SEC`,1010,1810);ctx.textAlign="left";
   };
   draw(0);recorder.start(250);source.start(startAt);await new Promise<void>(resolve=>{const tick=()=>{const elapsed=Math.max(0,audioContext!.currentTime-startAt);draw(elapsed);setRenderProgress(15+Math.round(Math.min(1,elapsed/duration)*82));if(elapsed<duration)requestAnimationFrame(tick);else resolve()};requestAnimationFrame(tick)});try{source.stop()}catch{}await new Promise(resolve=>setTimeout(resolve,180));recorder.stop();const blob=await finished;stream.getTracks().forEach(track=>track.stop());const url=URL.createObjectURL(blob);setVideoUrl(url);setRenderProgress(100);setStage("video");
  }catch(error){const code=error instanceof Error?error.message:"UNKNOWN";const message=code==="AI_SETUP_REQUIRED"?"Gemini API key is missing in Cloudflare.":code.includes("PERMISSION_DENIED")||code.includes("HTTP_403")?"Gemini TTS is not enabled for this API key/project.":code.includes("RESOURCE_EXHAUSTED")||code.includes("HTTP_429")?"Gemini TTS free quota is exhausted. Wait and try again.":code.includes("UNAUTHENTICATED")||code.includes("HTTP_401")?"Gemini rejected the API key.":code.includes("NotSupported")||code.includes("MediaRecorder")?"This browser cannot record WebM. Use current Chrome or Edge.":`Render stopped at: ${code}. Try once more; if it repeats, this code identifies the cause.`;setRenderError(message)}finally{if(audioContext)void audioContext.close();setRendering(false)}
 };
 return <main className="app-shell">
  <header className="masthead"><div className="logo"><span><Laugh size={22}/></span>WorldWise<em>STUDIO</em></div><div className="steps"><span className={stage!=="setup"?"done":"active"}><b>1</b> Script</span><i/><span className={stage==="video"||stage==="published"?"done":stage==="script"?"active":""}><b>2</b> Render</span><i/><span className={stage==="published"?"done":stage==="video"?"active":""}><b>3</b> Approve</span><i/><span className={stage==="published"?"active":""}><b>4</b> Publish</span></div><div className="head-actions"><button className="icon-button"><Search size={19}/></button><Button className="new-video"><Sparkles size={16}/> New video</Button><button className="menu"><Menu/></button></div></header>
  <div className="studio">
   <aside className="story-browser"><div className="browser-head"><div><span className="overline">LIVE NEWS FEED</span><h1>Choose a story</h1></div><button className="dots" onClick={()=>void refresh()} aria-label="Refresh news">{loading?<LoaderCircle className="spin"/>:<RefreshCw/>}</button></div><div className="source-status"><span className="pulse"/><b>{loading?"Scanning global coverage":`${stories.length} stories loaded`}</b><span>{feed}</span></div><div className="topic-tabs">{[["top","Top stories"],["world","World"],["science","Science"]].map(([id,label])=><button key={id} className={category===id?"selected":""} onClick={()=>{setCategory(id);void refresh(id)}}>{label}</button>)}</div>
    <div className="story-list">{stories.map(item=><button key={item.id} onClick={()=>choose(item.id)} className={`story ${selected===item.id?"selected":""}`}><span className={`story-mark ${item.accent}`}>{item.mark}</span><span className="story-copy"><span className="story-meta">{item.place} · {item.time}</span><strong>{item.title}</strong><span className="story-proof"><ShieldCheck size={14}/>{item.sources} coverage source{item.sources===1?"":"s"} <i>{item.verified?"Multi-source":"Needs verification"}</i></span></span></button>)}</div><button className="all-stories" onClick={()=>void refresh()}><Newspaper size={17}/> Refresh global news <ArrowRight size={16}/></button>
   </aside>
   <section className="canvas">
    <div className="canvas-top"><div><span className="overline">SELECTED STORY</span><div className="tags"><span>{story.topic}</span><span>{story.place}</span><span><Clock3/> {story.time}</span></div></div><button className="close"><X/></button></div>
    <div className="story-title"><h2>{story.title}</h2><p>{story.dek}</p>{story.url&&<a className="source-link" href={story.url} target="_blank" rel="noreferrer">Open original source · {story.domain}<ArrowRight/></a>}</div>
    {stage==="setup"&&<><div className="workflow-note"><span>1</span><div><b>Create a 30-second cartoon script and scene plan</b><p>Each scene visually matches the narration with animated characters and props.</p></div></div><div className="creation-layout"><div className="style-section"><span className="overline">VIDEO STYLE</span><h3>How should this story feel?</h3><div className="style-grid">{styles.map(s=><button key={s.id} onClick={()=>setVideoStyle(s.id)} className={videoStyle===s.id?"selected":""}><span>{s.icon}</span><b>{s.name}</b><small>{s.desc}</small>{videoStyle===s.id&&<i><Check/></i>}</button>)}</div><label>Voice</label><button className="select-control"><span><b>{voice}</b><small>English (US) · Conversational</small></span><ChevronDown/></button></div><div className={`poster ${story.accent}`}><div className="poster-top"><span>CARTOON PREVIEW</span><span>9:16</span></div><div className="poster-orbit"><span className="orb one"/><span className="orb two"/><span className="face"><b>{story.mark}</b></span></div><div className="poster-copy"><span>ANIMATED CARTOON</span><strong><>TODAY'S STORY<br/><u>IN 30</u> SECONDS.</></strong></div></div></div><div className="approval-bar"><div><ShieldCheck/><span><b>{story.verified?"Multi-source coverage detected":"Verification still required"}</b><small>Open the original source before approving factual claims.</small></span></div><div className="generate-wrap"><Button onClick={()=>void generateScript()} disabled={generating} className="create-button">{generating?<LoaderCircle className="spin"/>:<WandSparkles/>}{generating?"Writing script…":"Generate cartoon script & scenes"}{!generating&&<ArrowRight/>}</Button>{aiError&&<p className="ai-error">{aiError}</p>}</div></div></>}

    {stage==="script"&&<section className="draft full"><div className="stage-banner"><span>1</span><div><b>Review the script and cartoon scenes</b><p>Edit the words, then create the narration and 30-second video.</p></div><em>AWAITING APPROVAL</em></div><div className="draft-head"><div><span className="overline">SCRIPT & CARTOON PLAN</span><h3>Contextual animated cartoon · 30 seconds</h3></div><span className="draft-ready"><Check/> AI draft ready</span></div><div className="beats">{(aiPackage?.beats||beats.map(([time,label,narration])=>({time,label,narration,visual:"Visual direction pending"}))).map((beat,index)=><div className="beat" key={beat.label}><time>{beat.time}</time><b>{beat.label}</b><div><p contentEditable suppressContentEditableWarning onBlur={event=>updateBeat(index,event.currentTarget.textContent||"")}>{beat.narration}</p><small>{beat.visual}</small></div><button aria-label={`Preview ${beat.label}`}><CirclePlay/></button></div>)}</div>{aiPackage&&<div className="ai-notes"><b>Comedy angle</b><p>{aiPackage.humorAngle}</p>{aiPackage.safetyNotes.length>0&&<small>Review: {aiPackage.safetyNotes.join(" · ")}</small>}</div>}<div className="draft-footer"><button className="secondary" onClick={()=>setStage("setup")} disabled={rendering}>Change style</button><div className="assets"><span><Mic2/> Gemini narration</span><span><Globe2/> Contextual cartoon scenes</span></div><div className="render-action"><Button onClick={()=>void renderVideo()} disabled={rendering||!aiPackage} className="publish-button">{rendering?<LoaderCircle className="spin"/>:<Film/>}{rendering?`Rendering ${renderProgress}%`:"Approve & render cartoon"}</Button>{rendering&&<div className="render-meter"><i style={{width:`${renderProgress}%`}}/></div>}{renderError&&<p className="render-error">{renderError}</p>}</div></div></section>}

    {stage==="video"&&<section className="video-review"><div className="stage-banner"><span>2</span><div><b>Your real video is ready</b><p>Watch it, download the WebM file, and approve the result before publishing.</p></div><em>FINAL REVIEW</em></div><div className="review-grid"><div className="video-player">{videoUrl?<video ref={videoRef} src={videoUrl} controls playsInline preload="metadata"/>:<div className={`rendered-video ${story.accent}`}><LoaderCircle className="spin"/></div>}<a className="download-video" href={videoUrl} download={`${slug(aiPackage?.youtubeTitle||story.title)}.webm`}><Download/> Download video</a></div><div className="publish-card"><span className="overline">YOUTUBE DETAILS</span><h3>{story.title}</h3><label>Title</label><input defaultValue={aiPackage?.youtubeTitle||story.title}/><label>Description</label><textarea defaultValue={aiPackage?.youtubeDescription||story.dek}/><div className="check-row"><Check/> Narration, animated captions and source label included</div><Button disabled className="youtube-button"><Youtube/> YouTube connection comes next</Button><p className="publish-note">Download works now. Direct channel publishing will be enabled after YouTube OAuth is connected.</p><button className="secondary wide" onClick={()=>setStage("script")}>Back to script</button></div></div></section>}
   </section>
  </div>
 </main>
}
